apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: LoadBalancer  # 讓 Kubernetes 自動創建一個對外 IP
  selector:
    app: flask-app
  ports:
  - protocol: TCP
    port: 80  # 外部訪問的端口
    targetPort: 8080  # Flask 容器內的端口
